[package]
name = "multi-thread-problem"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
nalgebra = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 
chrono = "0.4"

[dev-dependencies]
approx = "0.4"